[package]
name = "wallet_kit"
version = "0.1.0"
edition = "2021"
description = "Solana toolkit for Not Wallet"
license = "MIT"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "wallet_kit"

[dependencies]
solana-sdk = "1.17.0"
solana-client = "1.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.35.1", features = ["full"] }
thiserror = "1.0.56"
log = "0.4.20"
bip39 = { version = "2", features = ["rand"] }
uniffi = { version = "0.29" }

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }
