name: "publish Android"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-android:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo tauri
        run: |
          cargo install tauri-cli --version "^2.0.0" --locked
          cargo tauri android init

      - name: Install frontend dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install OpenSSL (if needed)
        run: |
          if ! command -v openssl &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y openssl
          fi

      - name: Decrypt Android keystore
        run: |
          ./scripts/decrypt-keystore.sh \
            --encrypted ./secrets/upload-keystore.jks.gpg \
            --output ./upload-keystore.jks \
            --password ${{ secrets.KEYSTORE_ENCRYPTION_PASSWORD }}

      - name: Create keystore.properties
        run: |
          cat > src-tauri/gen/android/keystore.properties << EOF
          password=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=upload
          storeFile=${{ github.workspace }}/upload-keystore.jks
          EOF

      - name: Publish Android
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          pnpm publish-android
